### ISSUE TITLE
AMI Update: Create new revisions

### ISSUE THREAD

**Issue by patdunlavey** [esmero/ami#42]
Current behavior is that when AMI updates an existing object, a new revision is not created. This makes using AMI update a very risky proposition.

The feature request here is to either always create new revisions if revisioning is enabled, or provide a setting in the AMI set to enable or disable saving revisions.

Extra credit (another feature request): provide an action to roll back the most recent update process.

**Comment by DiegoPino** [comment]
@patdunlavey just to be sure, where in AMI are we setting no new revision to be created?
I thought we were respecting the Content Model (Bundle) decision by just saving. 
Can you test? Or show me where this happens?
The way to "force" a revision is a single line

$entity->setNewRevision(TRUE);

but if this is already respecting the global I would prefer we go for the global...

Roll back. If revisions are being respected you can make a VBO plugin that allows revisions to be reversed.. but its also tricky, since how do you know which ones to reverse? What if your AMI set failed and you reverse things that were not updated?

**Comment by DiegoPino** [comment]
@patdunlavey https://github.com/esmero/ami/commit/054c668a39a33c26339c165a0f11373688d7f0b5

**Comment by patdunlavey** [comment]
After further testing, it appears I was wrong. We are seeing new revisions, at least in small scale testing. Apologies for causing unnecessary panic! I'll close this now.
